// const promise = new Promise((resolve, reject) => {
//     setTimeout(() => {
//         resolve('This is my resolved data');
//     }, 5000);
// });

// const promise = new Promise((resolve, reject) => {
//     reject('id did not work');
// });

// console.log('before');

// promise.then((data) => {
//     console.log('1', data)
// }).catch((error) => {
//     console.log('ERROR: ', error);
// });

// console.log('after');
